### ISSUE TITLE
Allow sending output to stdout

### ISSUE THREAD

**Issue by abrkn** [eulerto/pgquarrel#50]
Debugging/summary/etc. should be sent to stderr. Can be made an option in ini

**Comment by eulerto** [comment]
@abrkn logXXX() and printSummary are sent to stderr. `verbose` defaults to false (check your ini file). You should also check `-v` option in command line because it enables debug messages. Errors are always printed. `summary` defaults to false (check your ini file). You should omit `-s` option in the command line to avoid summary.

**Comment by eulerto** [comment]
I added support to output to stdout by default (cf ee582636a57d4e19c93db3b0c7adfe12748c2dad and 95919f2de84bfa09403a82373e7a033e7bf8f90e). I also added a command line option (-f) for it.
