### ISSUE TITLE
Specifying certificates at connection

### ISSUE THREAD

**Issue by hyperknot** [eulerto/pgquarrel#76]
I'd like to connect to a PG server, which has certificates pinned down. 

psql connects with the following command:

```
psql "sslmode=verify-ca sslrootcert=server-ca.pem \
      sslcert=client-cert.pem sslkey=client-key.pem \
      hostaddr=x.x.x.x \
      user=x dbname=x"
```

Is it possibly for pgquarrel to specify these certificate files, and if so, how?

**Comment by eulerto** [comment]
> Is it possibly for pgquarrel to specify these certificate files, and if so, how?
>
Yes. `libpq` supports passing a connection string using `dbname`. Since `pgquarrel` uses it, you can use a configuration file including:

```
[target]
dbname = host=192.168.6.41 port=9901 user=quarrel dbname=quarrel1

[source]
dbname = host=192.168.6.50 port=9902 user=quarrel dbname=quarrel2
```
 
If you are using the command line options, use:

`pgquarrel -v -v --source-dbname "dbname = host=192.168.6.41 port=9901 user=quarrel dbname=quarrel1" --target-dbname "dbname = host=192.168.6.50 port=9902 user=quarrel dbname=quarrel2"`

**Comment by hyperknot** [comment]
Thanks, this works perfectly. So pretty much I only need dbname and password in config file.

BTW, what does -v -v do? Is it like -vv in some other apps?
